"""Corrected statistical analysis for the Wappingers Creek fault-salinity study.

Runs, for each upstream/downstream contrast:

  * Welch's two-sample t-test (unequal variance) -- the headline test. This is
    what the paper's Methods prose describes ("difference in means ... upstream
    and downstream"); the original code instead implemented a one-sample-style
    statistic t = (xbar2 - xbar1) / (s2 / sqrt(n2)), which inflated t.
  * Student's pooled two-sample t-test -- reported for completeness.
  * Mann-Whitney U -- nonparametric robustness check for the small samples.

It also recomputes the original (flawed) statistic so the correction is
transparent and auditable. Outputs a console summary and a LaTeX table written
to ``figures/table1_corrected.tex`` for \\input into main.tex.

Run:  .venv/bin/python src/stats.py
"""

from pathlib import Path
import numpy as np
from scipy import stats

from wappingers import load_salinity, zones, zones_as_published, CONTRASTS

OUT = Path(__file__).resolve().parent.parent / "figures" / "table1_corrected.tex"


def flawed_t(up, down):
    """The one-sample-style statistic the published statistics.R computed:
    t = (xbar2 - xbar1) / (s2 / sqrt(n2)) -- only the downstream group's
    spread enters the denominator."""
    return (down.mean() - up.mean()) / (down.std(ddof=1) / np.sqrt(len(down)))


def analyze():
    df = load_salinity()
    z = zones(df)
    zp = zones_as_published(df)  # normalized + original slices -> exact Table 1
    rows = []
    for name, a, b, kind in CONTRASTS:
        up, down = z[a], z[b]
        published_t = flawed_t(zp[a], zp[b])
        welch = stats.ttest_ind(down, up, equal_var=False)
        student = stats.ttest_ind(down, up, equal_var=True)
        mwu = stats.mannwhitneyu(down, up, alternative="two-sided")
        v1, v2, n1, n2 = up.var(ddof=1), down.var(ddof=1), len(up), len(down)
        welch_df = (v1 / n1 + v2 / n2) ** 2 / (
            (v1 / n1) ** 2 / (n1 - 1) + (v2 / n2) ** 2 / (n2 - 1)
        )
        rows.append(
            dict(
                contrast=name, zones=f"{a}, {b}", kind=kind,
                n_up=n1, n_down=n2,
                mean_up=up.mean(), mean_down=down.mean(),
                delta=down.mean() - up.mean(),
                welch_t=welch.statistic, welch_df=welch_df, welch_p=welch.pvalue,
                student_t=student.statistic, student_p=student.pvalue,
                mwu_p=mwu.pvalue,
                published_t=published_t,
            )
        )
    return rows


def fmt_p(p):
    return "<0.001" if p < 0.001 else f"{p:.3f}"


def print_summary(rows):
    print(f"{'C':3}{'zones':10}{'kind':11}{'n1':>3}{'n2':>3}"
          f"{'mean1':>9}{'mean2':>9}{'Δ':>7}"
          f"{'Welch t':>9}{'p':>8}{'MWU p':>8}{'pub. t':>9}  sig")
    for r in rows:
        sig = "YES" if r["welch_p"] < 0.05 else "no"
        print(f"{r['contrast']:3}{r['zones']:10}{r['kind']:11}"
              f"{r['n_up']:>3}{r['n_down']:>3}"
              f"{r['mean_up']:>9.1f}{r['mean_down']:>9.1f}{r['delta']:>7.1f}"
              f"{r['welch_t']:>9.2f}{fmt_p(r['welch_p']):>8}"
              f"{fmt_p(r['mwu_p']):>8}{r['published_t']:>9.2f}  {sig}")


def write_latex(rows):
    lines = [
        r"% Auto-generated by src/stats.py -- do not edit by hand.",
        r"\begin{tabular}{cclccrrrc}",
        r"\toprule",
        r"Contrast & Zones & Boundary & $n_1$ & $n_2$ & "
        r"$\bar{x}_1$ & $\bar{x}_2$ & Welch $t$ & $p$ \\",
        r"\midrule",
    ]
    for r in rows:
        p = r"$<$0.001" if r["welch_p"] < 0.001 else f"{r['welch_p']:.3f}"
        lines.append(
            f"{r['contrast']} & {r['zones']} & {r['kind']} & "
            f"{r['n_up']} & {r['n_down']} & "
            f"{r['mean_up']:.1f} & {r['mean_down']:.1f} & "
            f"{r['welch_t']:.2f} & {p} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    OUT.write_text("\n".join(lines) + "\n")
    print(f"\nWrote {OUT.relative_to(OUT.parents[1])}")


if __name__ == "__main__":
    rows = analyze()
    print_summary(rows)
    write_latex(rows)
